name: ft-transcendence-check

services:
  frontend:
    build: ./frontend
    volumes:
      - ./frontend/src:/app/src

  backend:
    build: ./backend
    volumes:
      - ./backend/src:/app/src
      - ./backend/prisma:/app/prisma
      - ./backend/test:/app/test
