name: ft-transcendence-check

services:
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - frontend_check_node_modules:/app/node_modules

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
      - backend_check_node_modules:/app/node_modules

volumes:
  frontend_check_node_modules:
  backend_check_node_modules:
